"use client";

import Link from "next/link";
import { ChevronLeft, ChevronRight } from "lucide-react";
import { useEffect, useState } from "react";

import { listProjects, type ApiProject } from "@/lib/api";

const pageSizes = [20, 50, 100];
const number = (value: string | number | null) => value === null || value === "" ? null : Number(value);
const value = (value: string | number | null, suffix = "") => { const parsed = number(value); return parsed === null || !Number.isFinite(parsed) ? "Not available" : `${parsed.toLocaleString("en-IN")}${suffix}`; };
const money = (value: string | number | null) => { const parsed = number(value); return parsed === null || !Number.isFinite(parsed) ? "Not available" : `₹${parsed.toLocaleString("en-IN")} Cr`; };

export default function ProjectsPage() {
  const [search, setSearch] = useState(""); const [state, setState] = useState(""); const [agency, setAgency] = useState(""); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20);
  const [data, setData] = useState<{ items: ApiProject[]; total: number; page: number; page_size: number } | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const controller = new AbortController(); const timer = window.setTimeout(() => { setLoading(true); setError(null); listProjects({ page, page_size: pageSize, search, state, implementing_agency: agency }, { signal: controller.signal }).then(setData).catch((reason) => { if (!controller.signal.aborted) setError(reason instanceof Error ? reason.message : "Projects could not be loaded."); }).finally(() => { if (!controller.signal.aborted) setLoading(false); }); }, 250); return () => { window.clearTimeout(timer); controller.abort(); }; }, [agency, page, pageSize, search, state]);
  const totalPages = Math.max(1, Math.ceil((data?.total ?? 0) / pageSize));
  const renderProjectRow = (project: ApiProject) => <tr key={project.id}><td><Link href={`/projects/${project.id}`} className="nd-project-name">{project.name || "Not available"}</Link><span className="nd-subtext">Code: {project.project_code || "Not available"}</span></td><td>{project.implementing_agency || "Not available"}</td><td>{project.state || "Not available"}</td><td className="nd-number">{money(project.original_cost)}</td><td className="nd-number">{money(project.current_cost)}</td><td className="nd-number">{value(project.physical_progress, "%")}</td><td><span className={`nd-status-label ${project.status ? "" : "neutral"}`}>{project.status || "Observed record"}</span></td></tr>;
  const hasSearch = search.trim().length > 0;
  return <div className="nd-page"><section className="nd-section nd-hero"><div className="nd-container nd-intro-grid"><div><p className="nd-eyebrow">Central monitoring / infrastructure register</p><h1 className="nd-title nd-title-small">Monitor projects.<br />Prioritize attention.</h1><p className="nd-lead">Search projects and review their current position.</p></div><aside className="nd-status-panel"><p className="nd-eyebrow">Project Register</p><strong>{data?.total?.toLocaleString("en-IN") || ""}</strong><p>Recorded infrastructure projects</p></aside></div></section>
    <section className="nd-section nd-section-tight"><div className="nd-container"><div className="nd-register-toolbar"><div className="nd-search-field"><label><span className="sr-only">Search project name</span><input className="nd-input" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); }} placeholder="Search project name" /></label>{hasSearch && <div className="nd-search-results" aria-live="polite">{loading ? <p className="nd-search-status">Searching...</p> : error ? <p className="nd-search-status">{error}</p> : data?.items.length ? data.items.map((project) => <Link href={`/projects/${project.id}`} className="nd-search-result" key={project.id}><strong>{project.name || "Not available"}</strong><span>{project.state || "State not available"} / {project.implementing_agency || "Agency not available"}{project.status ? ` / ${project.status}` : ""}</span></Link>) : <div className="nd-search-empty"><strong>No projects found</strong><span>Try a different project name.</span></div>}</div>}</div><label><span className="sr-only">Filter state</span><input className="nd-input" value={state} onChange={(event) => { setState(event.target.value); setPage(1); }} placeholder="State" /></label><label><span className="sr-only">Filter implementing agency</span><input className="nd-input" value={agency} onChange={(event) => { setAgency(event.target.value); setPage(1); }} placeholder="Implementing agency" /></label><label><span className="sr-only">Page size</span><select className="nd-select" value={pageSize} onChange={(event) => { setPageSize(Number(event.target.value)); setPage(1); }}>{pageSizes.map((size) => <option key={size} value={size}>{size} rows</option>)}</select></label></div></div></section>
    <section className="nd-section"><div className="nd-container">{error && !hasSearch ? <div className="nd-error">{error}</div> : loading && !data ? <div className="nd-empty">Loading project register...</div> : data && data.items.length === 0 ? <div className="nd-empty">No projects found<br /><span className="nd-subtext">Try a different project name.</span></div> : <><div className="nd-table-wrap"><table className="nd-table"><thead><tr><th>Project</th><th>Agency</th><th>State</th><th>Original cost</th><th>Current cost</th><th>Progress</th><th>Record</th></tr></thead><tbody>{data?.items.map(renderProjectRow)}</tbody></table></div><div className="nd-pagination"><span>{data?.total ? `${(page - 1) * pageSize + 1}-${Math.min(page * pageSize, data.total)} of ${data.total}` : "0 records"}</span><div className="nd-pagination-actions"><button className="nd-icon-button" aria-label="Previous page" disabled={page <= 1} onClick={() => setPage((current) => current - 1)}><ChevronLeft size={17} /></button><span>{page} / {totalPages}</span><button className="nd-icon-button" aria-label="Next page" disabled={page >= totalPages} onClick={() => setPage((current) => current + 1)}><ChevronRight size={17} /></button></div></div></>}</div></section>
  </div>;
}
